// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ittpgkoueigkrmnhmpfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0dHBna291ZWlna3JtbmhtcGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDQ0NDksImV4cCI6MjA1ODEyMDQ0OX0.W8y8mUQPTZ1VTskPxjizqe1352h5XTNqWfBXWQZiAzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);